### ISSUE TITLE
Trouble with setting up...

### ISSUE THREAD

**Issue by blackbelt626** [caliog/NPCLib#12]
I should mention that I'm still very new to writing plugins...

I'm planning on using this for a plugin for my own server. I have quite a "noob" question:

After reading through the forum thread, and downloading the lib into my project, it's full of errors and unrecognized imports. I have Bukkit in my build path, which is what I thought was needed for all Bukkit functionality, but that doesn't seem to be the case.

The lib also appears to be hooking "net.minecraft" classes. Where are these supposed to be coming from?

Any help or guidance would be greatly appreciated.

**Comment by caliog** [comment]
If you still need that information please open a new issue! (NPCLib will soon be updated to 1.8)
